### ISSUE TITLE
ptv2微调出错

### ISSUE THREAD

**Issue by ddzz0210** [ssbuild/moss_finetuning#12]
报错：AssertionError: No inf checks were recorded for this optimizer.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /hy-tmp/moss_finetuning-main/train.py:184 in <module>                                            │
│                                                                                                  │
│   181 │   )                                                                                      │
│   182 │                                                                                          │
│   183 │   if train_datasets is not None:                                                         │
│ ❱ 184 │   │   trainer.fit(pl_model, train_dataloaders=train_datasets)                            │
│   185                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py:520 in fit           │
│                                                                                                  │
│    517 │   │   """                                                                               │
│    518 │   │   model = _maybe_unwrap_optimized(model)                                            │
│    519 │   │   self.strategy._lightning_module = model                                           │
│ ❱  520 │   │   call._call_and_handle_interrupt(                                                  │
│    521 │   │   │   self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule,  │
│    522 │   │   )                                                                                 │
│    523                                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py:42 in                   │
│ _call_and_handle_interrupt                                                                       │
│                                                                                                  │
│    39 │   """                                                                                    │
│    40 │   try:                                                                                   │
│    41 │   │   if trainer.strategy.launcher is not None:                                          │
│ ❱  42 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer,    │
│    43 │   │   else:                                                                              │
│    44 │   │   │   return trainer_fn(*args, **kwargs)                                             │
│    45                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/strategies/launchers/subprocess_script. │
│ py:92 in launch                                                                                  │
│                                                                                                  │
│    89 │   │   """                                                                                │
│    90 │   │   if not self.cluster_environment.creates_processes_externally:                      │
│    91 │   │   │   self._call_children_scripts()                                                  │
│ ❱  92 │   │   return function(*args, **kwargs)                                                   │
│    93 │                                                                                          │
│    94 │   def kill(self, signum: _SIGNUM) -> None:                                               │
│    95 │   │   for proc in self.procs:                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py:559 in _fit_impl     │
│                                                                                                  │
│    556 │   │   │   model_provided=True,                                                          │
│    557 │   │   │   model_connected=self.lightning_module is not None,                            │
│    558 │   │   )                                                                                 │
│ ❱  559 │   │   self._run(model, ckpt_path=ckpt_path)                                             │
│    560 │   │                                                                                     │
│    561 │   │   assert self.state.stopped                                                         │
│    562 │   │   self.training = False                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py:935 in _run          │
│                                                                                                  │
│    932 │   │   # ----------------------------                                                    │
│    933 │   │   # RUN THE TRAINER                                                                 │
│    934 │   │   # ----------------------------                                                    │
│ ❱  935 │   │   results = self._run_stage()                                                       │
│    936 │   │                                                                                     │
│    937 │   │   # ----------------------------                                                    │
│    938 │   │   # POST-Training CLEAN UP                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py:978 in _run_stage    │
│                                                                                                  │
│    975 │   │   │   with isolate_rng():                                                           │
│    976 │   │   │   │   self._run_sanity_check()                                                  │
│    977 │   │   │   with torch.autograd.set_detect_anomaly(self._detect_anomaly):                 │
│ ❱  978 │   │   │   │   self.fit_loop.run()                                                       │
│    979 │   │   │   return None                                                                   │
│    980 │   │   raise RuntimeError(f"Unexpected state {self.state}")                              │
│    981                                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py:201 in run            │
│                                                                                                  │
│   198 │   │   while not self.done:                                                               │
│   199 │   │   │   try:                                                                           │
│   200 │   │   │   │   self.on_advance_start()                                                    │
│ ❱ 201 │   │   │   │   self.advance()                                                             │
│   202 │   │   │   │   self.on_advance_end()                                                      │
│   203 │   │   │   │   self._restarting = False                                                   │
│   204 │   │   │   except StopIteration:                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py:354 in advance        │
│                                                                                                  │
│   351 │   │   assert self._data_fetcher is not None                                              │
│   352 │   │   self._data_fetcher.setup(combined_loader)                                          │
│   353 │   │   with self.trainer.profiler.profile("run_training_epoch"):                          │
│ ❱ 354 │   │   │   self.epoch_loop.run(self._data_fetcher)                                        │
│   355 │                                                                                          │
│   356 │   def on_advance_end(self) -> None:                                                      │
│   357 │   │   trainer = self.trainer                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/training_epoch_loop.py:133 in run │
│                                                                                                  │
│   130 │   │   self.on_run_start(data_fetcher)                                                    │
│   131 │   │   while not self.done:                                                               │
│   132 │   │   │   try:                                                                           │
│ ❱ 133 │   │   │   │   self.advance(data_fetcher)                                                 │
│   134 │   │   │   │   self.on_advance_end()                                                      │
│   135 │   │   │   │   self._restarting = False                                                   │
│   136 │   │   │   except StopIteration:                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/training_epoch_loop.py:218 in     │
│ advance                                                                                          │
│                                                                                                  │
│   215 │   │   │   with trainer.profiler.profile("run_training_batch"):                           │
│   216 │   │   │   │   if trainer.lightning_module.automatic_optimization:                        │
│   217 │   │   │   │   │   # in automatic optimization, there can only be one optimizer           │
│ ❱ 218 │   │   │   │   │   batch_output = self.automatic_optimization.run(trainer.optimizers[0]   │
│   219 │   │   │   │   else:                                                                      │
│   220 │   │   │   │   │   batch_output = self.manual_optimization.run(kwargs)                    │
│   221                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/optimization/automatic.py:185 in  │
│ run                                                                                              │
│                                                                                                  │
│   182 │   │   # ------------------------------                                                   │
│   183 │   │   # gradient update with accumulated gradients                                       │
│   184 │   │   else:                                                                              │
│ ❱ 185 │   │   │   self._optimizer_step(kwargs.get("batch_idx", 0), closure)                      │
│   186 │   │                                                                                      │
│   187 │   │   result = closure.consume_result()                                                  │
│   188 │   │   if result.loss is None:                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/optimization/automatic.py:261 in  │
│ _optimizer_step                                                                                  │
│                                                                                                  │
│   258 │   │   │   self.optim_progress.optimizer.step.increment_ready()                           │
│   259 │   │                                                                                      │
│   260 │   │   # model hook                                                                       │
│ ❱ 261 │   │   call._call_lightning_module_hook(                                                  │
│   262 │   │   │   trainer,                                                                       │
│   263 │   │   │   "optimizer_step",                                                              │
│   264 │   │   │   trainer.current_epoch,                                                         │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py:142 in                  │
│ _call_lightning_module_hook                                                                      │
│                                                                                                  │
│   139 │   pl_module._current_fx_name = hook_name                                                 │
│   140 │                                                                                          │
│   141 │   with trainer.profiler.profile(f"[LightningModule]{pl_module.__class__.__name__}.{hoo   │
│ ❱ 142 │   │   output = fn(*args, **kwargs)                                                       │
│   143 │                                                                                          │
│   144 │   # restore current_fx when nested context                                               │
│   145 │   pl_module._current_fx_name = prev_fx_name                                              │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/core/module.py:1266 in optimizer_step   │
│                                                                                                  │
│   1263 │   │   │   │   │   for pg in optimizer.param_groups:                                     │
│   1264 │   │   │   │   │   │   pg["lr"] = lr_scale * self.learning_rate                          │
│   1265 │   │   """                                                                               │
│ ❱ 1266 │   │   optimizer.step(closure=optimizer_closure)                                         │
│   1267 │                                                                                         │
│   1268 │   def optimizer_zero_grad(self, epoch: int, batch_idx: int, optimizer: Optimizer) -> N  │
│   1269 │   │   """Override this method to change the default behaviour of ``optimizer.zero_grad  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/core/optimizer.py:158 in step           │
│                                                                                                  │
│   155 │   │   │   raise MisconfigurationException("When `optimizer.step(closure)` is called, t   │
│   156 │   │                                                                                      │
│   157 │   │   assert self._strategy is not None                                                  │
│ ❱ 158 │   │   step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)    │
│   159 │   │                                                                                      │
│   160 │   │   self._on_after_step()                                                              │
│   161                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/strategies/ddp.py:257 in optimizer_step │
│                                                                                                  │
│   254 │   │   │   model: reference to the model, optionally defining optimizer step related ho   │
│   255 │   │   │   **kwargs: Any extra arguments to ``optimizer.step``                            │
│   256 │   │   """                                                                                │
│ ❱ 257 │   │   optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)     │
│   258 │   │                                                                                      │
│   259 │   │   if self._model_averager is None:                                                   │
│   260 │   │   │   return optimizer_output                                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/strategies/strategy.py:224 in           │
│ optimizer_step                                                                                   │
│                                                                                                  │
│   221 │   │   model = model or self.lightning_module                                             │
│   222 │   │   # TODO(fabric): remove assertion once strategy's optimizer_step typing is fixed    │
│   223 │   │   assert isinstance(model, pl.LightningModule)                                       │
│ ❱ 224 │   │   return self.precision_plugin.optimizer_step(optimizer, model=model, closure=clos   │
│   225 │                                                                                          │
│   226 │   def _setup_model_and_optimizers(self, model: Module, optimizers: List[Optimizer]) ->   │
│   227 │   │   """Setup a model and multiple optimizers together.                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/lightning/pytorch/plugins/precision/amp.py:83 in          │
│ optimizer_step                                                                                   │
│                                                                                                  │
│    80 │   │   # in manual optimization, the closure does not return a value                      │
│    81 │   │   if not model.automatic_optimization or not skipped_backward:                       │
│    82 │   │   │   # note: the scaler will skip the `optimizer.step` if nonfinite gradients are   │
│ ❱  83 │   │   │   step_output = self.scaler.step(optimizer, **kwargs)                            │
│    84 │   │   │   self.scaler.update()                                                           │
│    85 │   │   │   return step_output                                                             │
│    86 │   │   return closure_result                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/cuda/amp/grad_scaler.py:339 in step                 │
│                                                                                                  │
│   336 │   │   if optimizer_state["stage"] is OptState.READY:                                     │
│   337 │   │   │   self.unscale_(optimizer)                                                       │
│   338 │   │                                                                                      │
│ ❱ 339 │   │   assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were rec   │
│   340 │   │                                                                                      │
│   341 │   │   retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)         │
│   342                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by ssbuild** [comment]
精度改成32 应该可以
