### ISSUE TITLE
请问是否支持通过直接微调MOSS Plugin INT4模型

### ISSUE THREAD

**Issue by lukaswangbk** [ssbuild/moss_finetuning#13]
作者您好，想请问一下
- 目前是否支持通过QLoRA的方式直接微调MOSS INT4的模型呢？
- 如果支持的话要怎么编写指令
- 并且需要的显存大概是多少呀

**Comment by ssbuild** [comment]
qlora 指的是[sft_config_lora_int4.py](https://github.com/ssbuild/moss_finetuning/blob/dev/config/sft_config_lora_int4.py)
修改config.__init__,py  导入sft_config_lora_int4.py模块即可。

**Comment by lukaswangbk** [comment]
好的感谢！请问是否支持INT4多卡微调呢

**Comment by ssbuild** [comment]
> 好的感谢！请问是否支持INT4多卡微调呢

可以
