### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by ddzz0210** [ssbuild/moss_finetuning#4]
运行train.py报错：'MyMossForCausalLM' object has no attribute 'enable_input_require_grads'，有什么办法解决吗？

**Comment by ddzz0210** [comment]
> 升级一下transformer

解决啦谢谢

再麻烦问一下，这个报错是为什么呢？
![微信图片_20230510092439](https://github.com/ssbuild/moss_finetuning/assets/128711621/c783c585-d9c3-4f5e-993a-fb57199dfdc6)

**Comment by ssbuild** [comment]
> > 升级一下transformer
> 
> 解决啦谢谢
> 
> 再麻烦问一下，这个报错是为什么呢？ ![微信图片_20230510092439](https://user-images.githubusercontent.com/128711621/237254762-c783c585-d9c3-4f5e-993a-fb57199dfdc6.png)

int4 只支持ptv2  对应修改 prompt_info_args 参数with_prompt 即可训练。
lora 需要加载官方的半精度权重

**Comment by ddzz0210** [comment]
> > > 升级一下transformer
> > 
> > 
> > 解决啦谢谢
> > 再麻烦问一下，这个报错是为什么呢？ ![微信图片_20230510092439](https://user-images.githubusercontent.com/128711621/237254762-c783c585-d9c3-4f5e-993a-fb57199dfdc6.png)
> 
> int4 只支持ptv2 对应修改 prompt_info_args 参数with_prompt 即可训练。 lora 需要加载官方的半精度权重

好的谢谢，我再试一下

**Comment by ddzz0210** [comment]
> > > 升级一下transformer
> > 
> > 
> > 解决啦谢谢
> > 再麻烦问一下，这个报错是为什么呢？ ![微信图片_20230510092439](https://user-images.githubusercontent.com/128711621/237254762-c783c585-d9c3-4f5e-993a-fb57199dfdc6.png)
> 
> int4 只支持ptv2 对应修改 prompt_info_args 参数with_prompt 即可训练。 lora 需要加载官方的半精度权重

不好意思，我又遇到了新的错误
我把lora改成False，prompt改成Ture
报以下错误：
![微信图片_20230510095536](https://github.com/ssbuild/moss_finetuning/assets/128711621/dc0c56a4-3381-4a46-b05b-3333bfee1555)
从这个位置开始的：
![微信图片_20230510095539](https://github.com/ssbuild/moss_finetuning/assets/128711621/59f92d15-b2f7-4052-8f02-ca3886f0987a)

**Comment by ssbuild** [comment]
> 

上传一下 lora_info_args prompt_info_args  train_info_args

**Comment by ddzz0210** [comment]
> > 
> 
> 上传一下 lora_info_args prompt_info_args train_info_args

![微信图片_20230510102213](https://github.com/ssbuild/moss_finetuning/assets/128711621/fa8967fd-b8fb-4a8e-af54-d725cef9e9f2)
![微信图片_20230510102216](https://github.com/ssbuild/moss_finetuning/assets/128711621/d1edf866-5f73-4e2d-8d60-6d6a0b6df1e1)
![微信图片_20230510102219](https://github.com/ssbuild/moss_finetuning/assets/128711621/8eb51e06-5b05-44a4-a081-298952d87e58)
![微信图片_20230510102223](https://github.com/ssbuild/moss_finetuning/assets/128711621/c86626b6-3a72-42a8-b087-63f69534dfc8)

**Comment by ssbuild** [comment]
https://github.com/ssbuild/moss_finetuning/blob/b4493d36348da6b38de96df2c201a7d94ef05ba9/models.py#L250

**Comment by ddzz0210** [comment]
> https://github.com/ssbuild/moss_finetuning/blob/b4493d36348da6b38de96df2c201a7d94ef05ba9/models.py#L250
> 
> 注释 self.model.enable_input_require_grads() 试试

int4 24g训练是不是不够呀，这回爆显存了

**Comment by ssbuild** [comment]
24不够。

**Comment by ddzz0210** [comment]
> 24不够。

好滴，那48行不

**Comment by ssbuild** [comment]
可以

**Comment by ddzz0210** [comment]
> 可以

谢谢，大佬辛苦！

**Comment by KyonCN** [comment]
> 可以

大佬，请问5张3090（24G）对003-base做fine tuning够吗，够就只申请这么多了。提前感谢
